### ISSUE TITLE
Segfaults on windows

### ISSUE THREAD

**Issue by jcrist** [mrocklin/sparse#19]
We were getting these for a while, then they went away after #12, and now they're back again: https://ci.appveyor.com/project/daskdev/dask/build/1.0.1278. Not sure if this is due to recent changes, or if we were just getting lucky before.

**Comment by mrocklin** [comment]
Sorry for leaving this unresolved.  My windows VM recently decided to fill up all of its disk space in a way that I'm unable to understand.  Working to get a new one.  This might be a bit.

**Comment by hameerabbasi** [comment]
@jcrist The AppVeyor builds seem to be succeeding now. Is it okay to close this?
