### ISSUE TITLE
Hard dependency on scipy.sparse?

### ISSUE THREAD

**Issue by jakevdp** [mrocklin/sparse#3]
It looks like you import scipy.sparse both locally and globally. I'd probably lean toward locally, to make scipy a soft dependency.

**Comment by mrocklin** [comment]
I think I started out as a soft dependency but transitioned to hard.  Tensordot and reductions currently depend on scipy.sparse.  These are important to me at the moment, but I can imagine that yes, they might not be important to all applications.

**Comment by jakevdp** [comment]
Makes sense. In that case there's an extra scipy import that you could remove in ``to_scipy_sparse``

**Comment by jakevdp** [comment]
fixed in d553026c3e77a170d9d4c759c93775f454b2c9ea
