### ISSUE TITLE
Support for triu/tril

### ISSUE THREAD

**Issue by jakirkham** [mrocklin/sparse#33]
Would be nice to have support for `triu` and `tril` functions to convert a dense Dask Array into a sparse one that only holds the upper or lower triangle respectively.

**Comment by mrocklin** [comment]
Is there a nice implementation of this somewhere for sparse arrays?

**Comment by jakirkham** [comment]
AFAICT SciPy just uses COO for this case. So I'm guessing this would work with what you already have here. These would just be convenience functions for getting that part of the array into COO form.

**Comment by hameerabbasi** [comment]
Implementing `triu` and `tril` for `COO` input/output seems trivial, even without looking at SciPy code, and I may take a look at it sometime. However, doing it on Dask arrays without converting them to `COO` in between seems like an edge use-case. If the original Dask array was dense, this would only result in a density of around `0.5`, in which case it is not a good idea to be using a sparse array anyway.

**Comment by hameerabbasi** [comment]
@jakirkham Okay to close this? We added `triu` and `tril` in #40.

**Comment by jakirkham** [comment]
Thanks for doing this @hameerabbasi. Is it possible to pass a vanilla array (e.g. NumPy) to these functions?

**Comment by hameerabbasi** [comment]
You can do something like `triu(COO.from_numpy(x))` for a dense array. But they don't directly support dense arrays.

**Comment by jakirkham** [comment]
Ok, thanks.

**Comment by hameerabbasi** [comment]
I would however say that if the original array is really dense (has a low number of nonzero elements), then using `COO` to store the upper/lower triangular parts is a bad idea since it will result in a sparsity of 0.5. I usually find `COO` is better in memory with a sparsity of 0.25 and better on most operations with a sparsity of 0.1.

**Comment by jakirkham** [comment]
Yeah I had been debating using this for triangular arrays and in the end decided it was better to just store them in flat 1-D arrays without coordinates as the transformation to 2-D arrays could be easily determined.
