### ISSUE TITLE
Current home of this repository?

### ISSUE THREAD

**Issue by hameerabbasi** [mrocklin/sparse#34]
There seem to be multiple homes for this repository. The PyPI page still refers to this one as the current home.

What is the current home for this project? I was considering adding broadcasting (as I needed it for a project of mine) and also contributing in other ways (I can add at least some of the things on #1 ). I can't seem to find the fork of this where my additions will have the maximum impact.

I would suggest that, at the very minimum, the PyPI should point to the current home of this project.

**Comment by mrocklin** [comment]
This is the current home
