### ISSUE TITLE
Not support converting to csr format currently? Can not index the element right?

### ISSUE THREAD

**Issue by ChaoYue0307** [mrocklin/sparse#36]
Just like the title describes, is it any way to access the element after construing the sparse matrix?

**Comment by mrocklin** [comment]
I recommend providing a minimal example that shows what you're attempting,
what you expect, and what you get.  https://stackoverflow.com/help/mcve

**Comment by hameerabbasi** [comment]
@ChaoYue0307 We can convert to CSR with `x.tocsr()` if `x` is `sparse.COO`. We can index the element with `x[1, 2].todense()[()]` (if `x` is 2-D and the indices are valid). We will find a way to make this easier in the future.

**Comment by hameerabbasi** [comment]
@ChaoYue0307 The `master` branch now supports indexing scalars (added in #57) and the `COO.tocsr()` method has existed for a long time.
