### ISSUE TITLE
General ``dot()``

### ISSUE THREAD

**Issue by jakevdp** [mrocklin/sparse#4]
With the ``reshape`` and ``transpose`` methods you have, it would be fairly trivial to generalize the ``dot()`` function to match the numpy result for multi-dimensional arrays. It might be worth adding!

**Comment by mrocklin** [comment]
See `sparse.tensordot` which implements everything already.  This was as you said, just an application of reshape and transpose.  I copied the existing numpy implementation almost verbatim.  

Or maybe you're already aware of this function, in which case I'm unaware of what missing functionality to which you're referring.

**Comment by jakevdp** [comment]
Ah, missed that. So it sounds like ``dot()`` should just wrap ``tensordot()``, making sure that the last dimension of ``x`` is multiplied with the second-to-last dimension of ``y``.

**Comment by mrocklin** [comment]
Done
