### ISSUE TITLE
requirements.txt is missing in PyPI

### ISSUE THREAD

**Issue by fujiisoup** [mrocklin/sparse#44]
Hi,

I tried to install sparse to a new (conda) environment by `pip install sparse`, but it fails with the following error.
```
Writing /tmp/easy_install-mhkizn5d/sparse-0.1.1/setup.cfg
Running sparse-0.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mhkizn5d/sparse-0.1.1/egg-dist-tmp-jpw672f1
error: [Errno 2] No such file or directory: 'requirements.txt'
```

The installation succeeds if the scipy and numpy are already installed in the environment.
I think we need to include `requirements.txt` in [MANIFEST.in](https://github.com/mrocklin/sparse/blob/master/MANIFEST.in).

**Comment by fujiisoup** [comment]
Closed. I did wired thing... Sorry for bothering.

**Comment by mrocklin** [comment]
I think you're still right though that we do need to include
requirements.txt in MANIFEST.in

**Comment by mrocklin** [comment]
https://github.com/mrocklin/sparse/pull/45

**Comment by fujiisoup** [comment]
I called this from my package and I thought a bug was my setup.py.
Thanks for the quick response :)
