### ISSUE TITLE
Release 0.2?

### ISSUE THREAD

**Issue by hameerabbasi** [mrocklin/sparse#52]
I was wondering if it might be wise at this point to release version 0.2 (after my current pull requests have been merged). All major operations have been added.

**Comment by mrocklin** [comment]
Yes, this seems reasonable to me.  I'm happy to go through the release
process whenever you get to a good stopping point.

**Comment by hameerabbasi** [comment]
I keep thinking of more and more things to add. I think the library is in a pretty mature state. Once #60 is closed, and #58 is merged, I'd be comfortable releasing version 0.2.

Then, the only things left (in my mind) for 0.9-ish would be adding more methods from `scipy.sparse`, which would just call the `scipy.sparse` equivalents, and also adding a `DOK` class which could be "frozen" or "unfrozen" from `COO`, which would only implement `__setitem__`.

**Comment by mrocklin** [comment]
Version 0.2.0 is tagged released on PyPI

See https://github.com/mrocklin/sparse/blob/master/release-procedure.md and https://github.com/mrocklin/sparse/blob/master/docs/changelog.rst

**Comment by hameerabbasi** [comment]
I was wondering about uploading documentation. This should be done with the release.

**Comment by mrocklin** [comment]
Yeah, the question then becomes "where should this go?"  Usually we would claim a name on readthedocs, like sparse.readthedocs.org.  However this is taken.  We would need to find a name.  Alternatively, if the talks with NumFOCUS go anywhere then maybe we can claim the name sparse.pydata.org (though I'm not sure that they'll want that to happen).

cc @rgommers

**Comment by hameerabbasi** [comment]
Not to put you on the spot, but how long do these things usually take?

**Comment by mrocklin** [comment]
Five minutes, once the necessary people all agree to decide to sit down and make a decision.  I've just sent another e-mail on the NumFOCUS thread.  

Also cc'ing @rgommers and @aterrel

**Comment by rgommers** [comment]
I think we're okay on the decision (@aterrel agreed?), just need to get you access to a repo and the domain name. I don't have admin access to those things myself. Hopefully @aterrel has time to do this, otherwise we need to ping another admin.

**Comment by mrocklin** [comment]
I think that may already have persmissions to do this (Jeff Reback gave me access a while ago).  I'm just waiting for authorization.  It sounds like I have it from @rgommers .  I've already spoken with @aterrel and he seemed fine with it as well, but I'll wait a few hours to give him a chance to change his mind.

**Comment by aterrel** [comment]
I'm fine with everything =D

**Comment by mrocklin** [comment]
I've moved this repository over to the pydata org.

I don't have access to the domain name though.  Someone needs to do this: http://docs.readthedocs.io/en/latest/alternate_domains.html#cname-support .  Andy, if you're busy I can ask around to see if I know anyone with access.

**Comment by mrocklin** [comment]
https://sparse-nd.readthedocs.org

**Comment by mrocklin** [comment]
https://sparse.pydata.org is live
