### ISSUE TITLE
Minimum version of scipy

### ISSUE THREAD

**Issue by fujiisoup** [mrocklin/sparse#65]
I noticed that we need at least scipy=0.19.
Can we update `requirements.txt` or work to support lower version of scipy?

**Comment by hameerabbasi** [comment]
Supporting legacy versions can be difficult. I'd prefer to just update `requirements.txt`, especially since no one I know in the Python community holds back on updates.

**Comment by mrocklin** [comment]
Either solution seems fine to me.  I agree with @hameerabbasi to use newer versions until someone arrives for whom this is a problem.

**Comment by mrocklin** [comment]
@fujiisoup any interest in submitting a tiny PR updating versions?
